require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Cap the local log file so it rotates instead of growing without bound.
  # Rails' own default is 100 MB per environment, each keeping one rotated
  # sibling, which is how ~400 MB of log accumulated per checkout in the one
  # environment nobody watches. Measured LOOSE by the hub archive sweep.
  #
  # THIS APP DOES CARRY studio-engine, whose `studio.logger` initializer caps
  # every consuming app — but only from 0.33.0, and the lock here resolves
  # 0.32.1, so nothing is capped today. The engine bump is its own change and
  # already has one: dependabot PR #28 (0.32.1 -> 0.74.11) moves 18 gems, which
  # does not belong in a local-disk chore. These literals match the engine's
  # DEVELOPMENT_MAX_BYTES / TEST_MAX_BYTES, and the engine initializer runs
  # AFTER environment files, so once that bump lands it simply sets the same
  # values and this block can go. Background: mcritchie-studio
  # docs/agents/maintenance/kickoff-log-rotation.md.
  #
  # `log_file_size` is the knob Rails' own :initialize_logger reads when it
  # builds the logger. Setting config.logger here instead would be a silent
  # no-op: :initialize_logger is a BOOTSTRAP initializer and has already run by
  # the time an engine or railtie initializer gets a turn. Environment files
  # load before it, which is why this works here.
  config.log_file_size = 16 * 1024 * 1024

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
